fix

diff --git a/.github/actions/get-terraform-plan/action.yml b/.github/actions/get-terraform-plan/action.yml
--- a/.github/actions/get-terraform-plan/action.yml
+++ b/.github/actions/get-terraform-plan/action.yml
@@ -23,6 +23,20 @@ runs:
       run: terraform init
       working-directory: ${{ inputs.tf_working_dir }}
       shell: bash
+    
+    - name: Extract region from terraform outputs
+      run: |
+        vallue=$(terraform output -raw region 2>/dev/null || echo "Output not found")
+        echo "region=$value" >> $GITHUB_ENV
+      working-directory: ${{ inputs.tf_working_dir }}
+      shell: bash
+
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: ${{ env.region }}
 
     - name: Terraform plan
       run: terraform plan -out tfplan.binary
