fix

diff --git a/.github/workflows/terraform-ouputs.yml b/.github/workflows/terraform-ouputs.yml
--- a/.github/workflows/terraform-ouputs.yml
+++ b/.github/workflows/terraform-ouputs.yml
@@ -35,10 +35,10 @@ jobs:
       - name: Get Specific Terraform Outputs
         id: terraform-outputs
         run: |
-            for key in $KEYS_OF_INTEREST; do
+            for output in $OUTPUTS_OF_INTEREST; do
               echo "ALOHA"
-              value=$(terraform output -raw $key 2>/dev/null || echo "Output not found")   #In bash, 1 means stdout, 2 means stderr(standard error stream). 2> /dev/null means that, redirect the error output from this command to /dev/null. Essentially meaning, just get rid of the error messages
-              echo "$key=$value" >> $GITHUB_ENV
+              value=$(terraform output -raw $output 2>/dev/null || echo "Output not found")   #In bash, 1 means stdout, 2 means stderr(standard error stream). 2> /dev/null means that, redirect the error output from this command to /dev/null. Essentially meaning, just get rid of the error messages
+              echo "$output=$value" >> $GITHUB_ENV
               echo "$value"
             done
       
